/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.awt.AWTUtilities;
import javax.swing.JOptionPane;
import rojeru_san.RSPanelsSlider;
        
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form crud
     */
    public formulario() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(this); 
        AWTUtilities.setWindowOpaque(this, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        rSButton_BTNCerrar = new rojeru_san.RSButton();
        rSButtonRiple_BTNSesion = new rojeru_san.RSButtonRiple();
        rSButtonRiple_BTNRegistrar = new rojeru_san.RSButtonRiple();
        rSPanelsSlider_PNLSlider = new rojeru_san.RSPanelsSlider();
        jPanel_PNLSesion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXT_Nombre = new rojeru_san.RSMTextFull();
        Pass_Contraseña = new rojeru_san.RSMPassView();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        jPanel_PNLRegistrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new rojeru_san.RSMTextFull();
        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        ID = new rojeru_san.RSMTextFull();
        Usuario = new rojeru_san.RSMTextFull();
        Contraseña = new rojeru_san.RSMPassView();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pc2.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ComponentesJD");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Compra donde los mejores ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        rSPanelShadow2.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(rSPanelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 10, -1, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButton_BTNCerrar.setBackground(new java.awt.Color(153, 0, 153));
        rSButton_BTNCerrar.setText("X");
        rSButton_BTNCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton_BTNCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton_BTNCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 11, 59, 24));

        rSButtonRiple_BTNSesion.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonRiple_BTNSesion.setText("Iniciar sesion");
        rSButtonRiple_BTNSesion.setColorHover(new java.awt.Color(240, 240, 240));
        rSButtonRiple_BTNSesion.setColorText(new java.awt.Color(153, 0, 153));
        rSButtonRiple_BTNSesion.setSelected(true);
        rSButtonRiple_BTNSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple_BTNSesionActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple_BTNSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 156, 153, -1));

        rSButtonRiple_BTNRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonRiple_BTNRegistrar.setText("Registrar usuario");
        rSButtonRiple_BTNRegistrar.setColorHover(new java.awt.Color(240, 240, 240));
        rSButtonRiple_BTNRegistrar.setColorText(new java.awt.Color(153, 0, 153));
        rSButtonRiple_BTNRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple_BTNRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple_BTNRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 153, -1));

        jPanel_PNLSesion.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_PNLSesion.setName("PNLSesion"); // NOI18N

        jLabel2.setBackground(new java.awt.Color(153, 0, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar sesion");

        TXT_Nombre.setModoMaterial(true);
        TXT_Nombre.setPlaceholder("Nombre de usuario...");

        Pass_Contraseña.setModoMaterial(true);
        Pass_Contraseña.setPlaceholder("Contraseña...");

        rSButtonRiple1.setBackground(new java.awt.Color(153, 0, 153));
        rSButtonRiple1.setText("Ingresar");
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PNLSesionLayout = new javax.swing.GroupLayout(jPanel_PNLSesion);
        jPanel_PNLSesion.setLayout(jPanel_PNLSesionLayout);
        jPanel_PNLSesionLayout.setHorizontalGroup(
            jPanel_PNLSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PNLSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PNLSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXT_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(Pass_Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PNLSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonRiple1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel_PNLSesionLayout.setVerticalGroup(
            jPanel_PNLSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PNLSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addComponent(TXT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pass_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(rSButtonRiple1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        rSPanelsSlider_PNLSlider.add(jPanel_PNLSesion, "card2");

        jPanel_PNLRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_PNLRegistrar.setName("jPanel_PNLRegistrar"); // NOI18N

        jLabel3.setBackground(new java.awt.Color(153, 0, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registrarse");

        Nombre.setModoMaterial(true);
        Nombre.setPlaceholder("Nombre... ");

        rSButtonRiple2.setBackground(new java.awt.Color(153, 0, 153));
        rSButtonRiple2.setText("Registrarme");

        ID.setModoMaterial(true);
        ID.setPlaceholder("Número de indetificación...");

        Usuario.setModoMaterial(true);
        Usuario.setPlaceholder("Nombre de usuario...");

        Contraseña.setModoMaterial(true);
        Contraseña.setPlaceholder("Contraseña...");

        javax.swing.GroupLayout jPanel_PNLRegistrarLayout = new javax.swing.GroupLayout(jPanel_PNLRegistrar);
        jPanel_PNLRegistrar.setLayout(jPanel_PNLRegistrarLayout);
        jPanel_PNLRegistrarLayout.setHorizontalGroup(
            jPanel_PNLRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PNLRegistrarLayout.createSequentialGroup()
                .addGroup(jPanel_PNLRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PNLRegistrarLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(rSButtonRiple2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_PNLRegistrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_PNLRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel_PNLRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_PNLRegistrarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_PNLRegistrarLayout.setVerticalGroup(
            jPanel_PNLRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PNLRegistrarLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonRiple2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_PNLRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_PNLRegistrarLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel3)
                    .addContainerGap(302, Short.MAX_VALUE)))
        );

        rSPanelsSlider_PNLSlider.add(jPanel_PNLRegistrar, "card3");

        jPanel1.add(rSPanelsSlider_PNLSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 41, -1, -1));

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton_BTNCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton_BTNCerrarActionPerformed
           System.exit(0);
    }//GEN-LAST:event_rSButton_BTNCerrarActionPerformed

    private void rSButtonRiple_BTNSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple_BTNSesionActionPerformed
        if (!this.rSButtonRiple_BTNSesion.isSelected()) {
            this.rSButtonRiple_BTNSesion.setSelected(true);
            this.rSButtonRiple_BTNRegistrar.setSelected(false);
            this.rSPanelsSlider_PNLSlider.setPanelSlider(5, jPanel_PNLSesion, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_rSButtonRiple_BTNSesionActionPerformed

    private void rSButtonRiple_BTNRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple_BTNRegistrarActionPerformed
        if (!this.rSButtonRiple_BTNRegistrar.isSelected()) {
            this.rSButtonRiple_BTNSesion.setSelected(false);
            this.rSButtonRiple_BTNRegistrar.setSelected(true);
            this.rSPanelsSlider_PNLSlider.setPanelSlider(5, jPanel_PNLRegistrar, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_rSButtonRiple_BTNRegistrarActionPerformed

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
    
        String user = TXT_Nombre.getText();
        String pass = Pass_Contraseña.getText();
        String us = "JD300";
        String pss = "GTX500";
        
        if (user.equals("") || pass.equals("")) {
            
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
        }
        else{
            if (user.equals(us) && pass.equals(pss)) {
                
                //formulario_CRUD fcrd = new formulario_CRUD();
                //fcrd.setVisible(true);
            }
        }
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.RSMPassView Contraseña;
    public rojeru_san.RSMTextFull ID;
    public rojeru_san.RSMTextFull Nombre;
    public rojeru_san.RSMPassView Pass_Contraseña;
    public rojeru_san.RSMTextFull TXT_Nombre;
    public rojeru_san.RSMTextFull Usuario;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_PNLRegistrar;
    private javax.swing.JPanel jPanel_PNLSesion;
    public rojeru_san.RSButtonRiple rSButtonRiple1;
    public rojeru_san.RSButtonRiple rSButtonRiple2;
    public rojeru_san.RSButtonRiple rSButtonRiple_BTNRegistrar;
    public rojeru_san.RSButtonRiple rSButtonRiple_BTNSesion;
    public rojeru_san.RSButton rSButton_BTNCerrar;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojeru_san.RSPanelsSlider rSPanelsSlider_PNLSlider;
    // End of variables declaration//GEN-END:variables
}
